version: "3.8"
services:
    angular:
        build: 
            context: ./app
            dockerfile: Dockerfile
        ports: 
            - 4200:4200
            - 49153:49153
        volumes:
            - ./app/src:/usr/app/src
            - ./app/package.json:/usr/app/package.json
    express:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports: 
            - 80:3000
        volumes:
            - ./public:/express/public
            - ./server/models:/express/models
            - ./server/routes:/express/routes
            - ./server/app.js:/express/app.js
            - ./server/package.json:/express/package.json
        depends_on: 
            - angular
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes: 
            - type: volume
              source: mongo_db
              target: /data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

volumes: 
    mongo_db:
        external: true