version: "3.8"
services:
    angular:
        build: 
            context: ./app
            dockerfile: Dockerfile
        ports: 
            - 4200:4200
            - 4201:49153
        volumes:
            - ./app/:/usr/app/
        entrypoint: ./entrypoint.sh
    express:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports: 
            - 80:3000
        volumes:
            - ./public:/express/public
            - ./server/:/express
        depends_on: 
            - angular
        entrypoint: ./entrypoint.sh
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes: 
            - type: volume
              source: mongo_db
              target: /data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

volumes: 
    mongo_db:
        external: true
    exclude: